### ISSUE TITLE
Error: URL doesn't link to the actual GitHub pages site

### ISSUE THREAD

**Issue by AluminiumTech** [evilarceus/EvilPanel#1]
So I tried the link in the description and it doesn't work. it says that the site doesn't exist.

![error404](https://cloud.githubusercontent.com/assets/14107316/20170943/624bc264-a769-11e6-8c10-2e3b24c666da.PNG)

**Comment by evilarceus** [comment]
That's normal. Once I populate the gh-pages branch it should work :)
